use_frameworks!

platform :ios, '8.0'

target 'LGWebImage_Example' do
  pod 'LGWebImage', :path => '../'

  target 'LGWebImage_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
